#!/bin/bash
#PBS -l nodes=4:ppn=12
#PBS -l walltime=00:02:00
#PBS -q batch
#PBS -N o
#PBS -j oe

#export OMP_NUM_THREADS=4
cd ~/ParallelProgrammingFinal
mpiexec -np 4 --map-by ppr:1:node --hostfile $PBS_NODEFILE ./rp.cx 10

#mpiexec -np 2 --map-by ppr:1:node --hostfile $PBS_NODEFILE valgrind --tool=memcheck --leak-check=yes -v --leak-check=full --track-origins=yes --log-file=vg.%p ./mp.cx 10

