#!/bin/bash
#PBS -l nodes=10:ppn=12
#PBS -l walltime=00:01:00
#PBS -q batch
#PBS -N out
#PBS -j oe

cd ~/ParallelProgrammingFinal
mpiexec -np 10 --map-by ppr:1:node --hostfile $PBS_NODEFILE ./qp.cx 100
