#!/bin/bash
#PBS -l nodes=1:ppn=12
#PBS -l walltime=00:01:00
#PBS -q batch
#PBS -N out
#PBS -j oe

cd ~/ParallelProgrammingFinal
mpiexec -np 1 --map-by ppr:1:node --hostfile $PBS_NODEFILE ./quick.cx 10000000

